name: "Zaya Fireplace Bluetooth Bridge"
version: "0.1.3"  
slug: "zaya_fireplace_bridge"
description: "Control Zaya Bluetooth Fireplace via Bluetooth using MQTT"

startup: services
init: false

arch:
  - aarch64
  - armv7
  - amd64

host_network: true

full_access: true           # Docker'da --privileged gibi, donanıma tam erişim
privileged:                 # rfcomm için network/admin hakları
  - NET_ADMIN
  - SYS_ADMIN


options:
  fireplace_mac: "0A:B0:76:CC:A3:7D"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "mqtt_user"
  mqtt_password: "mqtt_pass"
  mqtt_command_topic: "zaya/fireplace/command"
  mqtt_state_topic: "zaya/fireplace/state"

schema:
  fireplace_mac: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_command_topic: str
  mqtt_state_topic: str
